# Introduction

This report on data governance in **{{< meta country >}}** is part of the “Harnessing Data for Democratic Development in South and Southeast Asia” (D4DAsia) project, which aims, *inter alia*, to create and mobilize new knowledge about tensions, gaps, and the evolution of the data governance ecosystem, taking into account formal and informal policies and practices.

In today's digital age, data governance ecosystems play a crucial role in shaping our societies. These ecosystems, comprising policies, laws, practices, behaviors, and technologies, aim to govern data in ways that protect rights, foster innovation, enhance transparency, and ultimately promote democratic and inclusive governance. However, the landscape of data governance is complex and often fraught with challenges, particularly in South and Southeast Asia.

A data governance ecosystem comprises the policies, laws, practices, behaviors, and technologies that govern data. An ideal data governance system would protect rights, enable innovation, enhance transparency, and contribute to achieving democratic and inclusive governance. Throughout the remainder of the report, unless the context indicates otherwise, the term “policies” is used as shorthand for policies, statutes, regulations, rules, administrative orders, and even practices and technologies used to implement these as part of the data governance ecosystem.

Data is increasingly being recognized as an enabler for development. It is an essential requirement for policymaking and monitoring of development goals and targets. When effectively managed, data can be used as an asset to support significant development actions such as poverty reduction, food security, mitigating the impact of climate change, and disaster management. If mismanaged, it can exacerbate inequalities and undermine the development potential of the same actions.

The D4DAsia project has produced nine reports so far — seven detailed individual country reports which deal with the issues of data governance in the following countries: India, Indonesia, Nepal, Pakistan, Philippines, Sri Lanka and Thailand; a detailed look at data protection in South Korea; and a synthesis report that summarizes the findings from the various countries while drawing out the contrasts amongst them, along with detailed findings to the research questions we posed, which were:

1.  What is common, and what is nationally specific, in the emerging data governance architectures in South and Southeast Asia? What are the explanations?

2.  What are the implications of the emergent nature of the governance architecture? Because there is no overall design that envisions how the parts fit together, it is likely that there will be friction points and even contradictions. How are these being worked out?

3.  The emerging governance architecture involves trade-offs among objectives such as greater accountability of powerholders, economic growth, including the creation of employment and wealth, resilience of systems, etc. How have different societies: (a) explicitly recognized the trade-offs or not; and (b) handled them?

4.  Are there legislative or policy innovations with potential for replication? What are the modalities of sharing experiences? Are developing countries learning from each other, or are they learning from the developed countries?

5.  How were the laws and bills developed? What expertise was brought to bear? How open were the procedures? How receptive were drafters to suggestions and criticisms?

6.  How were capacity challenges addressed: by simplifying the laws or by tolerating incomplete implementation?

## Structure of the report

### Governance background

The report starts by providing contextual information about the constitution and governance framework in **{{< meta country >}}**, including how lawmaking powers are distributed and delegated, the powers of the judiciary to overturn laws or to enforce policies, and the legal and regulatory background in the country.

### Increasing openness / access

The report then discusses policies that increase openness or access. By this, we mean policies that allow greater access by citizens, consumers, and corporations to data, or facilitate interoperability or cross-border data transfer. Specifically, we do not include increased governmental access to citizens’ private data or non-public corporate data.

This section discusses open data policies, the question of how much governmental data is made available proactively, and how much is reactive as well as the quality of data being disseminated. The report also assesses government policies favoring or requiring free and open source software (FOSS) or open standards, noting any specific standards that are mandated.

### Decreasing openness/access

The report then moves on to discuss the opposite, i.e., laws, policies, and practices which decrease openness or access. By this we mean decreasing access of citizens, consumers, and corporations to data. To be clear, this is not a negative value judgement, since upholding important individual and collective rights, such as privacy and public security, necessitates reducing citizens’ access to data.

This theme explores issues of security, such as whether there are any data retention or localization requirements, restrictions on the right to access information (such as national security, privacy, etc.) and exceptions to data security requirements for law enforcement. We further discuss the privacy and copyright framework in brief and specifically try to answer whether there are any exceptions for search engines as well as for research and artificial intelligence (AI).

::: {.content-visible when-meta="country:Pakistan"}
The last part of the report consists of a deep dive examining the policy gaps and frictions in the data governance framework.
:::

::: {.content-visible when-meta="country:Sri Lanka"}
The final section of the report provides a comprehensive examination of the policy gaps and frictions within the data governance framework. Here, we conducted a detailed analysis of two critical legislative frameworks:

-   The Right to Information (RTI) Act, its implementation, and its role in enhancing transparency.

-   The Personal Data Protection Act, its provisions, and its implications for privacy and data governance.

The report concludes with a summary of key findings, highlighting areas of progress, and existing challenges.
:::

The issue of data governance and the policies surrounding its implementation is critical for governments, citizens, and businesses across the world. As mentioned earlier, we use the term data governance to refer to “diverse arrangements, including technical, policy, regulatory or institutional provisions, that affect data and their creation, collection, storage, use, protection, access, sharing and deletion across policy domains and organizational and national borders” [@oecdGoingDigital2022].

::: {.content-visible when-meta="country:Sri Lanka"}
## Methodology and limitations

This study was conducted through a combination of legal and policy analysis and interviews with selected key stakeholders. The report seeks to present a nuanced understanding of the existing data governance framework, highlighting areas of successful implementation as well as gaps.

It is important to note that the majority of this research was conducted in late 2023 and early 2024 and reflects the state of policies during that time; there have been amendments and updates since that may not be discussed below. We have included some recent updates, such as the Draft Cloud Strategy released in June 2025. Additionally, some policies/draft policies mentioned below may no longer be accessible on official websites due to subsequent policy updates.
:::